// Final Column Order
export const FINAL_HEADERS = [
  "No",
  "Date",
  "Group",
  "Kanal",
  "MetodeBayar",
  "Toko",
  "Team",
  "ADV",
  "PLATFORM",
  "PlatformCrm",
  "NamaCS",
  "TypeTransaksi",
  "OrderNumber",
  "Awb",
  "CustomerPhoneNumber",
  "CustomerDisplayName",
  "BillingAddress",
  "Note",
  "ProductCode",
  "Quantity",
  "UnitPrice",
  "Totalperline",
  "Ekspedisi",
  "Ongkir",
  "DiscountOngkir",
  "CODFee",
  "Discount Fee COD",
  "ShippingFee",
  "Total+ShippingFee",
  "Warehouse",
  "BM PER TEAM",
  "NAMA CS",
  "PRODUK",
  "CLOSING",
  "JENIS INPUT",
  "ADV_PLATFORM",
  "Status",
  "Last CRM",
  "Last Team",
  "KecamatanCustomer",
  "KabupatenCustomer",
  "ProvinsiCustomer",
  "source",
];
